-- Supabase/PostgreSQL Database Schema Setup
-- Run this script in the Supabase SQL Editor to initialize all tables, seed data, and fix the "Could not find the table in schema cache" error.

-- 1. Create Tables

CREATE TABLE IF NOT EXISTS company_settings (
  id integer PRIMARY KEY CHECK (id = 1),
  name text NOT NULL,
  address text,
  phone text,
  email text,
  gstin text,
  pan text,
  bank_name text,
  bank_branch text,
  account_name text,
  account_no text,
  ifsc_code text
);

CREATE TABLE IF NOT EXISTS clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  contact_person text,
  mobile text NOT NULL,
  email text,
  address text NOT NULL,
  city text NOT NULL,
  state text,
  pin text NOT NULL,
  gstin text,
  pan text
);

CREATE TABLE IF NOT EXISTS invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no text UNIQUE NOT NULL,
  invoice_date text NOT NULL,
  client_id bigint NOT NULL,
  po_no text,
  po_date text,
  tax_type text NOT NULL, -- 'CGST_SGST', 'IGST', 'NONE'
  cgst_rate numeric DEFAULT 9,
  sgst_rate numeric DEFAULT 9,
  igst_rate numeric DEFAULT 18,
  subtotal numeric NOT NULL,
  cgst_amount numeric DEFAULT 0,
  sgst_amount numeric DEFAULT 0,
  igst_amount numeric DEFAULT 0,
  gross_total numeric NOT NULL,
  FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  sr integer NOT NULL,
  "desc" text NOT NULL,
  hsn text,
  qty numeric NOT NULL,
  rate numeric NOT NULL,
  total numeric NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS quotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_no text UNIQUE NOT NULL,
  quotation_date text NOT NULL,
  valid_until text NOT NULL,
  client_id bigint NOT NULL,
  tax_type text NOT NULL, -- 'CGST_SGST', 'IGST', 'NONE'
  cgst_rate numeric DEFAULT 9,
  sgst_rate numeric DEFAULT 9,
  igst_rate numeric DEFAULT 18,
  subtotal numeric NOT NULL,
  cgst_amount numeric DEFAULT 0,
  sgst_amount numeric DEFAULT 0,
  igst_amount numeric DEFAULT 0,
  gross_total numeric NOT NULL,
  status text NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'ACCEPTED', 'DECLINED'
  FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id bigint NOT NULL,
  sr integer NOT NULL,
  "desc" text NOT NULL,
  hsn text,
  qty numeric NOT NULL,
  rate numeric NOT NULL,
  total numeric NOT NULL,
  FOREIGN KEY (quotation_id) REFERENCES quotations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  date text NOT NULL,
  read boolean DEFAULT false
);


-- 2. Seed Default Data

-- Seed default settings
INSERT INTO company_settings (id, name, address, phone, email, gstin, pan, bank_name, bank_branch, account_name, account_no, ifsc_code)
VALUES (
  1,
  'EVER READY ENGINEERS',
  'Plate no 192/1, sr.no 1 Nilai nivas Nagarsolapur road, Mirajaon, Ahilyanagar -414402',
  '8888162227',
  'erengieners01@gmail.com',
  '27FBFD9897L1Z5',
  'FBFD9897L',
  'Ahilyanagar co-operative bank',
  'Chincholi Kaldat',
  'Ever Ready Engineers',
  '02161102100018',
  'AHDC0000216'
) ON CONFLICT (id) DO NOTHING;

-- Seed default notifications
INSERT INTO notifications (id, type, title, message, date, read)
VALUES 
(1, 'payment_due', 'Payment Due', 'INV-001 is due on 04-07-2026', '2 hours ago', false),
(2, 'quote_expiring', 'Quote Expiring', 'QUO-001 expires in 5 days', '5 hours ago', false)
ON CONFLICT (id) DO NOTHING;

-- Seed default clients
INSERT INTO clients (id, name, contact_person, mobile, email, address, city, state, pin, gstin, pan)
VALUES 
(1, 'TATA MOTORS LTD', 'R. K. Sharma', '9822012345', 'tata.motors@tata.com', 'Pimpri Industrial Area Sector A', 'Pune', 'Maharashtra', '411018', '27AAAAT1234A1Z1', 'AAAT1234A'),
(2, 'RELIANCE INDUSTRIES', 'A. K. Ambani', '8888888888', 'info@ril.com', 'Ghansoli', 'Navi Mumbai', 'Maharashtra', '400701', '27AAACR4321B1Z2', 'AAACR4321B')
ON CONFLICT (id) DO NOTHING;

-- Seed default invoices
INSERT INTO invoices (id, invoice_no, invoice_date, client_id, po_no, po_date, tax_type, cgst_rate, sgst_rate, igst_rate, subtotal, cgst_amount, sgst_amount, igst_amount, gross_total)
VALUES (1, 'INV-101', '2026-06-01', 1, 'PO-TATAMOTORS-99', '2026-05-28', 'CGST_SGST', 9, 9, 18, 1200000, 108000, 108000, 0, 1416000)
ON CONFLICT (id) DO NOTHING;

-- Seed default invoice_items
INSERT INTO invoice_items (id, invoice_id, sr, "desc", hsn, qty, rate, total)
VALUES (1, 1, 1, 'Precision Lathe Machining Work', '8466', 2, 600000, 1200000)
ON CONFLICT (id) DO NOTHING;

-- Seed default quotations
INSERT INTO quotations (id, quotation_no, quotation_date, valid_until, client_id, tax_type, cgst_rate, sgst_rate, igst_rate, subtotal, cgst_amount, sgst_amount, igst_amount, gross_total, status)
VALUES (1, 'QUO-101', '2026-06-03', '2026-07-03', 2, 'IGST', 9, 9, 18, 360000, 0, 0, 64800, 424800, 'PENDING')
ON CONFLICT (id) DO NOTHING;

-- Seed default quotation_items
INSERT INTO quotation_items (id, quotation_id, sr, "desc", hsn, qty, rate, total)
VALUES (1, 1, 1, 'Industrial Laser Cutting & Welding Services', '8456', 3, 120000, 360000)
ON CONFLICT (id) DO NOTHING;


-- 3. Align identity column sequences (important to prevent duplicate key errors on new inserts)
SELECT setval(pg_get_serial_sequence('clients', 'id'), coalesce(max(id), 1)) FROM clients;
SELECT setval(pg_get_serial_sequence('invoices', 'id'), coalesce(max(id), 1)) FROM invoices;
SELECT setval(pg_get_serial_sequence('invoice_items', 'id'), coalesce(max(id), 1)) FROM invoice_items;
SELECT setval(pg_get_serial_sequence('quotations', 'id'), coalesce(max(id), 1)) FROM quotations;
SELECT setval(pg_get_serial_sequence('quotation_items', 'id'), coalesce(max(id), 1)) FROM quotation_items;
SELECT setval(pg_get_serial_sequence('notifications', 'id'), coalesce(max(id), 1)) FROM notifications;


-- 4. Disable Row Level Security (RLS) for Development
-- (Allows access using the anonymous key without needing complex Auth/Policies setup)
ALTER TABLE company_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE quotation_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- 5. Add Payments and Comments Tables (Phase 1 & 2 Upgrade)
CREATE TABLE IF NOT EXISTS invoice_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  payment_date text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0),
  payment_mode text NOT NULL CHECK (payment_mode IN ('CASH', 'UPI', 'BANK_TRANSFER', 'CHEQUE', 'CARD', 'OTHER')),
  reference_number text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoice_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  comment text NOT NULL,
  comment_type text NOT NULL CHECK (comment_type IN ('NOTE', 'PAYMENT', 'SYSTEM')),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_invoice_payments_invoice_id ON invoice_payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_comments_invoice_id ON invoice_comments(invoice_id);

-- Align identity sequences
SELECT setval(pg_get_serial_sequence('invoice_payments', 'id'), coalesce(max(id), 1)) FROM invoice_payments;
SELECT setval(pg_get_serial_sequence('invoice_comments', 'id'), coalesce(max(id), 1)) FROM invoice_comments;

-- Disable RLS
ALTER TABLE invoice_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_comments DISABLE ROW LEVEL SECURITY;


-- 6. Add Discount & Transport Charges columns (Phase 3 Upgrade)
-- Run this block if you are upgrading from a previous schema version.
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS discount NUMERIC DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS transport_charges NUMERIC DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS discount NUMERIC DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS transport_charges NUMERIC DEFAULT 0;
